# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-23 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
        ('registration', '0002_auto_20170123_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOtherDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=50, null=True)),
                ('works', models.CharField(max_length=100, null=True)),
                ('lives', models.CharField(max_length=50, null=True)),
                ('followers', models.IntegerField(null=True)),
                ('facebook_link', models.CharField(max_length=100, null=True)),
                ('twitter_link', models.CharField(max_length=100, null=True)),
                ('linked_in_profile', models.CharField(max_length=100, null=True)),
                ('most_active_topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.User')),
            ],
        ),
    ]
