# Generated by Django 2.1.1 on 2018-09-21 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('answers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alreadyreadanswers',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_alreadyreadanswers_related', to='answers.Answer'),
        ),
        migrations.AddField(
            model_name='alreadyreadanswers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_alreadyreadanswers_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
