# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userotherdetails_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotherdetails',
            name='display_picture',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
