# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170210_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotherdetails',
            name='following',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
