# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userotherdetails_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotherdetails',
            name='profile_no_of_views',
            field=models.IntegerField(null=True),
        ),
    ]
