# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userotherdetails_profile_no_of_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotherdetails',
            name='profile_no_of_views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
