# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20170210_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotherdetails',
            name='display_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
