# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20170210_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotherdetails',
            name='no_of_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userotherdetails',
            name='no_of_questions',
            field=models.IntegerField(default=0),
        ),
    ]
