# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20170212_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotherdetails',
            name='followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userotherdetails',
            name='following',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
