# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20170212_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotherdetails',
            name='display_picture',
            field=models.ImageField(null=True, upload_to='dps'),
        ),
    ]
