# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20170212_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotherdetails',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userotherdetails',
            name='college',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userotherdetails',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userotherdetails',
            name='followers',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userotherdetails',
            name='following',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userotherdetails',
            name='linked_in_profile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userotherdetails',
            name='lives',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userotherdetails',
            name='most_active_topic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='topics.Topic'),
        ),
        migrations.AlterField(
            model_name='userotherdetails',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userotherdetails',
            name='works',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
