# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20170212_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotherdetails',
            name='college',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='userotherdetails',
            name='display_picture',
            field=models.ImageField(default='NA', upload_to='dps'),
        ),
        migrations.AlterField(
            model_name='userotherdetails',
            name='facebook_link',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='userotherdetails',
            name='linked_in_profile',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='userotherdetails',
            name='lives',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='userotherdetails',
            name='most_active_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topics.Topic'),
        ),
        migrations.AlterField(
            model_name='userotherdetails',
            name='twitter_link',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='userotherdetails',
            name='works',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
    ]
