# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20170212_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_userfollowings', to='account.UserOtherDetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_userfollowings_related', to='account.UserOtherDetails')),
            ],
        ),
    ]
