# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20170220_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotherdetails',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userotherdetails',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
