# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_userfollowings_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicfollowing',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userfollowings',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
