# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20170222_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicfollowing',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='topicfollowing',
            name='user',
        ),
        migrations.DeleteModel(
            name='TopicFollowing',
        ),
    ]
