# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0015_auto_20170213_2212'),
        ('account', '0024_auto_20170304_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlreadyReadAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_alreadyreadanswers_related', to='answers.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_alreadyreadanswers_related', to='account.UserOtherDetails')),
            ],
        ),
        migrations.AlterField(
            model_name='userfollowings',
            name='is_following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_userfollowings', to='account.UserOtherDetails'),
        ),
        migrations.AlterField(
            model_name='userfollowings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_userfollowings_related', to='account.UserOtherDetails'),
        ),
    ]
