# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_usernotifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alreadyreadanswers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_alreadyreadanswers_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
