# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_questiontopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='no_of_views',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='no_following_quest',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='no_of_answers',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
