# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20170128_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_asked',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='time_asked',
            field=models.TimeField(null=True),
        ),
    ]
