# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20170128_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
    ]
