# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_remove_question_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date_asked', '-time_asked']},
        ),
    ]
