# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_questionimageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
