# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20170307_2122'),
        ('questions', '0011_question_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserOtherDetails')),
            ],
        ),
    ]
