# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_readquestions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date_asked']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='time_asked',
        ),
        migrations.AlterField(
            model_name='question',
            name='date_asked',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
