# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20170404_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfollowing',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
