# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20170407_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfollowing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
