# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_remove_answer_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='no_of_comments',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='no_of_upvotes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='no_of_views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
