# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 02:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answers', '0003_auto_20170131_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
