# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0004_answer_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_string',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
