# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0005_answer_question_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_string',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
