# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0006_auto_20170207_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='edited',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
