# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0007_answer_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='no_of_downvotes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
