# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0008_answer_no_of_downvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='writer_string',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
