# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0012_auto_20170210_1323'),
        ('account', '__first__')
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.UserOtherDetails'),
        ),
    ]
