# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0013_auto_20170212_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='date_written',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='time_written',
        ),
    ]
