# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 22:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answers', '0016_auto_20170313_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestEdits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('original_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_suggestedits_op_related', to=settings.AUTH_USER_MODEL)),
                ('suggester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_suggestedits_suggester_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.Answer')),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_thanks_answerer_related', to=settings.AUTH_USER_MODEL)),
                ('asker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_thanks_sender_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
