# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0017_suggestedits_thanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedits',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='answers.Answer'),
        ),
    ]
