# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0018_suggestedits_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thanks',
            old_name='asker',
            new_name='user',
        ),
    ]
