# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0020_anonymousanswerwriters'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
