# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-23 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('image_url', models.TextField()),
                ('no_following_topic', models.IntegerField()),
                ('no_of_questions_under_topic', models.IntegerField()),
            ],
        ),
    ]
