# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
