# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20170126_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='no_following_topic',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='no_of_questions_under_topic',
            field=models.IntegerField(null=True),
        ),
    ]
