# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20170127_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='image_url',
        ),
        migrations.AddField(
            model_name='topic',
            name='image_name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
