# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
