# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privatemessages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationreplies',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
